load("@adder_tree//:defs.bzl", "adder_tree")
load("@delay_line//:defs.bzl", "delay_line")
load("@multiplier_layer//:defs.bzl", "multiplier_layer")
load("@register_file//:defs.bzl", "register_file")
load("//tools/bazel:sv_rules.bzl", "sv_jinja_inline_template", "sv_library")

package(default_visibility = ["//visibility:public"])

TOP_CONFIG = {
    "MODULE_NAME": "generic_fp_rd",
    "DELAY_LINE_MODULE_NAME": "fp_rd_delay",
    "REGISTER_FILE_MODULE_NAME": "fp_rd_compute",
    "MULTIPLIER_LAYER_MODULE_NAME": "fp_rd_compute",
    "ADDER_TREE_MODULE_NAME": "fp_rd_sum",
    "TAPS_COUNT": "16",
    "INPUT_DATA_WIDTH": "16",
    "COEFFS_WIDTH": "16",
    "MUL_OUTPUT_DATA_WIDTH": "32",
    "HAS_RESET": "true",
    "DELAY_LINE_HAS_RESET": "false",
    "HAS_ENABLE": "true",
    "HAS_DATA_VALIDITY": "true",
    "HAS_COEFFS_OUTPUT": "false",
}

DELAY_CONFIG = {
    "MODULE_NAME": "fp_rd_delay",
    "DATA_WIDTH": 16,
    "TAPS_COUNT": 8,
    "HAS_RESET": False,
    "HAS_ENABLE": True,
    "HAS_DATA_VALIDITY": True,
    "HAS_BYPASS": False,
    "HAS_TAP_OUTPUTS": True,
}

REGISTER_FILE_CONFIG = {
    "MODULE_NAME": "fp_rd_compute",
    "TAPS_COUNT": 8,
    "COEFFS_WIDTH": 16,
    "COEFF_TYPE": "DYNAMIC",
    "COEFFS_DEFAULT_VALUES": [0, 0, 0, 0, 0, 0, 0, 0],
    "COEFFS_CONST_TYPE": "dec",
    "COEFFS_CONST_TYPE_IS_SIGNED": True,
    "HAS_RESET": False,
    "HAS_ENABLE": True,
    "HAS_SHADOW_REGISTERS": False,
    "COEFFS_OPTIONS_COUNT": 0,
}

MULTIPLIER_CONFIG = {
    "MODULE_NAME": "fp_rd_compute",
    "TAPS_COUNT": 8,
    "INPUT_DATA_WIDTH": 16,
    "COEFFS_WIDTH": 16,
    "OUTPUT_DATA_WIDTH": 32,
    "MUL_MODE": "COMB",
    "HAS_REGISTER_OUTPUTS": True,
    "HAS_RESET": False,
    "HAS_ENABLE": True,
    "HAS_DATA_VALIDITY": True,
    "CUSTOM_EN": False,
    "TARGET": "VERIFICATION",
}

ADDER_CONFIG = {
    "MODULE_NAME": "fp_rd_sum",
    "INPUT_COUNT": 8,
    "DATA_WIDTH": 32,
    "FIXED_LAYER_DATA_WIDTH": False,
    "ADDER_MODE": "COMB",
    "HAS_RESET": False,
    "HAS_ENABLE": True,
    "HAS_DATA_VALIDITY": True,
    "START_OUTPUT_LAYER": 3,
    "TARGET": "VERIFICATION",
    "CUSTOM_EN": False,
}

delay_line(
    name = "delay_line",
    params = DELAY_CONFIG,
)

register_file(
    name = "register_file",
    params = REGISTER_FILE_CONFIG,
)

multiplier_layer(
    name = "multiplier_layer",
    params = MULTIPLIER_CONFIG,
)

adder_tree(
    name = "adder_tree",
    params = ADDER_CONFIG,
)

sv_jinja_inline_template(
    name = "generic_fp_rd_top",
    template = "top.sv.j2",
    config = TOP_CONFIG,
    deps = [
        ":adder_tree_library",
        ":delay_line_library",
        ":multiplier_layer_library",
        ":register_file_library",
        "//tools/jinja2:jinja2_utils",
    ],
    out = "generic_fp_rd.sv",
)

sv_library(
    name = "rtl",
    deps = [":generic_fp_rd_top"],
)

multiplier_layer(
    name = "fpga_multiplier_layer",
    params = dict(MULTIPLIER_CONFIG, TARGET = "FPGA"),
)

adder_tree(
    name = "fpga_adder_tree",
    params = dict(ADDER_CONFIG, TARGET = "FPGA"),
)

sv_jinja_inline_template(
    name = "fpga_top",
    template = "top.sv.j2",
    config = TOP_CONFIG,
    deps = [
        ":delay_line_library",
        ":fpga_adder_tree_library",
        ":fpga_multiplier_layer_library",
        ":register_file_library",
        "//tools/jinja2:jinja2_utils",
    ],
    out = "fpga/generic_fp_rd.sv",
)

sv_library(
    name = "fpga_rtl",
    deps = [":fpga_top"],
)
