load("//tools/bazel:sv_rules.bzl", "sv_jinja_inline_template", "sv_library")
load("//tools/bazel:fpga_filter_rules.bzl", "fpga_filter_rtl")

package(default_visibility = ["//visibility:public"])

TOP_CONFIG = {
    "MODULE_NAME": "generic_fp_rd",
    "DELAY_LINE_MODULE_NAME": "fp_rd_delay",
    "MULTIPLIER_LAYER_MODULE_NAME": "fp_rd_compute",
    "ADDER_TREE_MODULE_NAME": "fp_rd_sum",
    "TAPS_COUNT": "16",
    "INPUT_DATA_WIDTH": "16",
    "COEFFS_WIDTH": "16",
    "MUL_OUTPUT_DATA_WIDTH": "32",
    "HAS_RESET": "true",
    "DELAY_LINE_HAS_RESET": "false",
    "HAS_ENABLE": "true",
    "HAS_DATA_VALIDITY": "true",
    "HAS_COEFFS_OUTPUT": "false",
}

DELAY_CONFIG = {
    "MODULE_NAME": "fp_rd_delay",
    "DATA_WIDTH": "16",
    "TAPS_COUNT": "8",
    "HAS_RESET": "false",
    "HAS_ENABLE": "true",
    "HAS_DATA_VALIDITY": "true",
    "HAS_BYPASS": "false",
    "HAS_TAP_OUTPUTS": "true",
}

MULTIPLIER_CONFIG = {
    "MODULE_NAME": "fp_rd_compute",
    "TAPS_COUNT": "8",
    "INPUT_DATA_WIDTH": "16",
    "COEFFS_WIDTH": "16",
    "OUTPUT_DATA_WIDTH": "32",
    "MUL_MODE": "COMB",
    "REGISTER_OUTPUTS": "true",
    "COEFF_TYPE": "DYNAMIC",
    "COEFFS_CONST_TYPE": "dec",
    "COEFFS_CONST_TYPE_IS_SIGNED": "true",
    "HAS_RESET": "false",
    "HAS_ENABLE": "true",
    "HAS_DATA_VALIDITY": "true",
    "HAS_SHADOW_REGISTERS": "false",
    "HAS_COEFFS_OPTIONS": "false",
    "COEFFS_OPTIONS_COUNT": "0",
    "HAS_COEFFS_OUTPUT": "false",
    "CUSTOM_EN": "false",
    "TARGET": "VERIFICATION",
}

ADDER_CONFIG = {
    "MODULE_NAME": "fp_rd_sum",
    "INPUT_COUNT": "8",
    "DATA_WIDTH": "32",
    "FIXED_LAYER_DATA_WIDTH": "false",
    "ADDER_MODE": "COMB",
    "HAS_RESET": "false",
    "HAS_ENABLE": "true",
    "HAS_DATA_VALIDITY": "true",
    "START_OUTPUT_LAYER": "3",
    "TARGET": "VERIFICATION",
    "CUSTOM_EN": "false",
}

sv_jinja_inline_template(
    name = "delay_cell",
    template = "//src/common/delay_line:src/cell.sv.j2",
    config = DELAY_CONFIG,
    deps = ["//tools/jinja2:jinja2_utils"],
    out = "fp_rd_delay_line_cell.sv",
)

sv_jinja_inline_template(
    name = "delay_line",
    template = "//src/common/delay_line:src/top.sv.j2",
    config = DELAY_CONFIG,
    deps = [
        ":delay_cell",
        "//tools/jinja2:jinja2_utils",
    ],
    out = "fp_rd_delay.sv",
)

sv_jinja_inline_template(
    name = "multiplier_pkg",
    template = "//src/common/multiplier_layer:src/multiplier_layer_pkg.sv.j2",
    config = MULTIPLIER_CONFIG,
    deps = ["//tools/jinja2:jinja2_utils"],
    out = "fp_rd_compute_multiplier_layer_pkg.sv",
)

sv_jinja_inline_template(
    name = "multiplier_register_file",
    template = "//src/common/multiplier_layer:src/register_file.sv.j2",
    config = MULTIPLIER_CONFIG,
    deps = [
        ":multiplier_pkg",
        "//tools/jinja2:jinja2_utils",
    ],
    out = "fp_rd_compute_register_file.sv",
)

sv_jinja_inline_template(
    name = "multiplier_wrapper",
    template = "//src/common/multiplier_layer:src/multiplier_wrapper.sv.j2",
    config = MULTIPLIER_CONFIG,
    deps = [
        ":multiplier_pkg",
        "//tools/jinja2:jinja2_utils",
    ],
    out = "fp_rd_compute_multiplier_wrapper.sv",
)

sv_jinja_inline_template(
    name = "multiplier_layer",
    template = "//src/common/multiplier_layer:src/multiplier_layer.sv.j2",
    config = MULTIPLIER_CONFIG,
    deps = [
        ":multiplier_pkg",
        ":multiplier_register_file",
        ":multiplier_wrapper",
        "//tools/jinja2:jinja2_utils",
    ],
    out = "fp_rd_compute_multiplier_layer.sv",
)

sv_jinja_inline_template(
    name = "adder_wrapper",
    template = "//src/common/adder_tree:src/adder_wrapper.sv.j2",
    config = ADDER_CONFIG,
    deps = ["//tools/jinja2:jinja2_utils"],
    out = "fp_rd_sum_adder_wrapper.sv",
)

sv_jinja_inline_template(
    name = "adder_tree",
    template = "//src/common/adder_tree:src/adder_tree.sv.j2",
    config = ADDER_CONFIG,
    deps = [
        ":adder_wrapper",
        "//tools/jinja2:jinja2_utils",
    ],
    out = "fp_rd_sum_adder_tree.sv",
)

sv_jinja_inline_template(
    name = "generic_fp_rd_top",
    template = "top.sv.j2",
    config = TOP_CONFIG,
    deps = [
        ":adder_tree",
        ":delay_line",
        ":multiplier_layer",
        "//tools/jinja2:jinja2_utils",
    ],
    out = "generic_fp_rd.sv",
)

sv_library(
    name = "rtl",
    deps = [":generic_fp_rd_top"],
)

fpga_filter_rtl(
    top_template = "top.sv.j2",
    top_config = TOP_CONFIG,
    multiplier_config = MULTIPLIER_CONFIG,
    adder_config = ADDER_CONFIG,
    multiplier_pkg = ":multiplier_pkg",
    multiplier_deps = [":multiplier_register_file"],
    top_deps = [":delay_line"],
)
