load("//tools/bazel:sv_rules.bzl", "sv_jinja_inline_template")
load("//tools/bazel:sv_rules.bzl", "sv_library")

package(default_visibility = ["//visibility:public"])

BASE_CONFIG = {
    "MODULE_ID": "generic",
    "DATA_WIDTH": "16",
    "COEFF_WIDTH": "16",
    "COEFFS_COUNT": "16",
    "MUL_DATA_WIDTH": "32",
    "COEFF_DEFAULT_VALUE": "0",
    "CELL_RESET_EN": "true",
    "CELL_ENABLE_EN": "true",
    "CELL_INPUT_DATA_EN": "true",
    "CELL_NEXT_CELL_OUTPUT_EN": "true",
    "CELL_COEFF_UPDATE_EN": "true",
    "CELL_MULTIPLY_EN": "true",
    "CELL_NEXT_CELL_OUTPUT_DATA_SELECTOR_EN": "true",
    "CELL_EXT_COEFFS_EN": "true",
    "CELL_MULTIPLY_OUTPUT_EN": "true",
    "CELL_COEFF_OUTPUT_EN": "true",
}

sv_jinja_inline_template(
    name = "generic_filter_cell",
    template = "src/cell.sv.j2",
    config = BASE_CONFIG,
    deps = ["//tools/jinja2:jinja2_utils"],
    out = "generic_filter_cell.sv",
)

sv_library(
    name = "rtl",
    deps = [":generic_filter_cell"],
)
