load("//tools/bazel:sv_rules.bzl", "sv_jinja_inline_template", "sv_library")

package(default_visibility = ["//visibility:public"])

BASE_CONFIG = {
    "MODULE_NAME": "generic",
    "COEFFS_WIDTH": "16",
    "COEFFS_OPTIONS_COUNT": "2",
    "TAPS_COUNT": "16",
    "INPUT_DATA_WIDTH": "16",
    "OUTPUT_DATA_WIDTH": "32",
    "MUL_MODE": "COMB",
    "REGISTER_OUTPUTS": "true",
    "HAS_RESET": "false",
    "HAS_ENABLE": "true",
    "HAS_DATA_VALIDITY": "true",
    "HAS_COEFFS_OPTIONS": "false",
    "HAS_COEFFS_OUTPUT": "false",
    "COEFF_TYPE": "DYNAMIC",
    "COEFFS_CONST_TYPE": "dec",
    "COEFFS_CONST_TYPE_IS_SIGNED": "true",
    "HAS_SHADOW_REGISTERS": "false",
    "CUSTOM_EN": "false",
    "TARGET": "VERIFICATION",
}

sv_jinja_inline_template(
    name = "generic_multiplier_layer_pkg",
    template = "src/multiplier_layer_pkg.sv.j2",
    config = BASE_CONFIG,
    deps = ["//tools/jinja2:jinja2_utils"],
    out = "generic_multiplier_layer_pkg.sv",
)

sv_jinja_inline_template(
    name = "generic_register_file",
    template = "src/register_file.sv.j2",
    config = BASE_CONFIG,
    deps = ["//tools/jinja2:jinja2_utils"],
    out = "generic_register_file.sv",
)

sv_jinja_inline_template(
    name = "generic_coeffs_selector",
    template = "src/coeffs_selector.sv.j2",
    config = BASE_CONFIG,
    deps = ["//tools/jinja2:jinja2_utils"],
    out = "generic_coeffs_selector.sv",
)

sv_jinja_inline_template(
    name = "generic_multiplier_wrapper",
    template = "src/multiplier_wrapper.sv.j2",
    config = BASE_CONFIG,
    deps = ["//tools/jinja2:jinja2_utils"],
    out = "generic_multiplier_wrapper.sv",
)

sv_jinja_inline_template(
    name = "generic_multiplier_layer",
    template = "src/multiplier_layer.sv.j2",
    config = BASE_CONFIG,
    deps = ["//tools/jinja2:jinja2_utils"],
    out = "generic_multiplier_layer.sv",
)

sv_library(
    name = "rtl",
    deps = [
        ":generic_multiplier_layer_pkg",
        ":generic_register_file",
        ":generic_coeffs_selector",
        ":generic_multiplier_wrapper",
        ":generic_multiplier_layer",
    ],
)
