load("@hdl_rules//filelist:defs.bzl", "verilog_filelist")
load("@hdl_rules//verilog:defs.bzl", "verilog_library")

package(default_visibility = ["//visibility:public"])

verilog_library(
    name = "rtl",
    deps = ["//src/filters:rtl"],
)

verilog_filelist(
    name = "filelist",
    deps = [":rtl"],
    out = "rtl.f",
)
